name: "amass"
description: "The OWASP Amass Project performs network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques"
branding:
  icon: "activity"
  color: "blue"

inputs:

  domain:
    description: "domain to enumerate"
    required: false   

  output:
    description: "File to save output result"
    required: false
    default: "amass-result.txt"   

  config:
    description: "Path to the INI configuration file."
    required: false     


runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/gau ] && go install -v github.com/OWASP/Amass/v3/...@master
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        /home/runner/go/bin/amass enum -src  -config=${{ inputs.config }} -o=${{ inputs.output }}      
      shell: bash
