name: "amass"
description: "The OWASP Amass Project performs network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques"
branding:
  icon: "activity"
  color: "blue"

inputs:

  domain:
    description: "domain to enumerate"
    required: false   

  output:
    description: "File to save output result"
    required: false
    default: "amass-result.txt"   




runs:
  using: "composite"
  steps:
    - run: |
        [ ! -x /home/runner/go/bin/gau ] && go install -v github.com/OWASP/Amass/v3/...@master
        [ ! -z ${{ inputs.domain }} ] && echo "domain=-d=${{ inputs.domain }} " >> $GITHUB_ENV                                                                   
        [ ! -z ${{ inputs.output }} ] && echo "output=-o=${{ inputs.output }} " >> $GITHUB_ENV   
        echo "/home/runner/go/bin/" >> $GITHUB_PATH
      shell: bash

    - run: |
        /home/runner/go/bin/amass enum -src -brute -ipv4 -d=${{ inputs.domain }} -o=${{ inputs.output }}      
      shell: bash
